[package]
name = "hostimg"
version = "0.1.0"
authors = ["Emil Hernvall <emil@c0la.se>"]

[dependencies]
image = "0.12.3"
sha2 = "0.4.2"
rusqlite = "0.9.5"
tiny_http = "0.5"
handlebars = "0.15.0"
regex = "0.2"
rustc-serialize = "0.3"
ascii = "0.5.0"
